### ISSUE TITLE
Server Improvements

### ISSUE THREAD

**Issue by sagar-wal** [saisumith770/form-example-golang-react#2]
- [x] Add error handling for all operations in backend (for eg. c.BindJSON), and print appropriate log messages on error.
- [x] Replace fmt.Println with log library of Golang.

**Comment by saisumith770** [comment]
resolved the issues in this [commit](https://github.com/saisumith770/form-example-golang-react/commit/7940f00fcf16f1174073a494e24ec8b70c99af7b)
